plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/caijunchang/Desktop/📂專案/ai-resource-packs/示範網站"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]